name: Report an issue with the Telegram Bot
description: Somethings not quite right with the Satisfactory Telegram Bot? Create a report for it now!
labels:
  - bug
body:
  - type: markdown
    attributes:
      value: |
        This issue form is for reporting bugs on the Telegram Bot only!

        If you have a feature or enhancement request, or want to report something wrong with the Gameserver images itself, please use the [official channel][official].

        [official]: https://questions.satisfactorygame.com/search?category=dedicated%20servers&date=All%20Time&status=open
  - type: textarea
    validations:
      required: true
    attributes:
      label: The problem
      description: >-
        Please describe the issue you are experiencing, including as many details as possible.
        Tell us what you were trying to do and what happened.

        Provide a clear and concise description of what the problem is.
  - type: markdown
    attributes:
      value: |
        ## Environment
  - type: input
    id: version
    validations:
      required: true
    attributes:
      label: What version has the issue?
      placeholder: f.ex. 2022.1.1
      description: >
        You can find the version by running `docker ps` and looking at the `tag` of your running container instance.
  - type: input
    attributes:
      label: What was the last working version?
      placeholder: f.ex. 2022.1.1
      description: >
        If known, otherwise leave blank.
  - type: dropdown
    validations:
      required: true
    attributes:
      label: What type of installation are you running?
      description: >
        You probably use the container.
      options:
        - Container
        - Native
        - Other (please describe below)

  - type: markdown
    attributes:
      value: |
        ## Details

  - type: textarea
    attributes:
      label: Anything in the logs that might be useful for us?
      description: For example, error message, or stack traces.
      render: raw
  - type: textarea
    attributes:
      label: Additional information
      description: >
        If you have any additional information for us, use the field below.