name: Docker Server

on:
  push:
    tags:
      - "server-*/*"

env:
  REGISTRY: ghcr.io

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Figure out release tag
        id: prep
        if: github.event_name == 'push' && contains(github.ref, 'refs/tags/')
        run: |
          RELEASE_BRANCH=${GITHUB_REF_NAME%%/*}
          RELEASE_VERSION=${GITHUB_REF_NAME#*/}
          echo ::set-output name=branch::${RELEASE_BRANCH}
          echo ::set-output name=version::${RELEASE_VERSION}

      - name: Log into registry ${{ env.REGISTRY }}
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository }}/${{ steps.prep.outputs.branch }}
          tags: |
            type=raw,value=${{ steps.prep.outputs.version }}

      - name: Build and push Docker image
        id: build-and-push
        uses: docker/build-push-action@v5
        with:
          context: .
          file: satisfactory.Dockerfile
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          build-args: RELEASE_BRANCH=${{ steps.prep.outputs.branch }}
